### ISSUE TITLE
alternatives!

### ISSUE THREAD

**Issue by pajooh** [novapost/django-generic-filters#31]
can you compare this package with more known [django-filter](https://github.com/alex/django-filter)

**Comment by Natim** [comment]
Basically the main difference is the faceting.

**Comment by benoitbryon** [comment]
It could be nice to have it reviewed and documented in docs/about/alternatives.
At the beginning of the project (as far as I remember), the main difference was django-generic-filters was using forms to validate filter input. The idea was "use forms to easily collect and validate filters for queryset in ListView". Not sure it makes the difference today: https://django-filter.readthedocs.org/en/latest/usage.html#custom-forms-using-form
