### ISSUE TITLE
Do distinct only when needed

### ISSUE THREAD

**Issue by rodo** [novapost/django-generic-filters#38]
The `DISTINCT` clause is not necessary where there is no AGGREGAT or COUNT, and must not be added on all queries. Adding a `DISTINCT` kill performance mostly with `ORDER BY`.

https://github.com/novapost/django-generic-filters/blob/master/django_genericfilters/views.py#L136

**Comment by boblefrag** [comment]
The decision we have taken about distinct is : this is not the scope of django-generic-filter to "distinct" the queryset. Django generic filter only return non-evaluated queryset. This is the scope of the application using django-generic-filter to make distinct if needed.

This is the reason why I will close this ticket. Do not hesitate to open it again if needed

**Comment by rodo** [comment]
Totally agree with this position, to be as clear as possible I mention here for history that the `distinct` was removed in https://github.com/novapost/django-generic-filters/commit/28a23e5ebe3a4dae534bc7f4adf1b30960ec6caf
